---
title: "Monte Carlo Simulation"
author: "Your name"
format: html
---

# Polymer Chains

(Adapted from Monte Carlo Simulation: An Introduction for Engineers and Scientists by Alan Stevens, Chapter 11)

Polymers are large molecules comprised of a large number of repeated units (monomers) linked end to end. 
There are naturally occurring polymers, such as cellulose, and artificial polymers, such as polythene (polyethylene). 
A simple model of a polymer assumes its linked units are each oriented completely randomly with respect to each other. 
This results in a nearly infinite number of configurations.

Suppose the goal is to estimate the straight-line distance between the start and end of the polymer chain. 
The theoretical probability density function for this distance is $$P(R) = 4\pi R^2\left(\frac{3}{2\pi\langle r^2\rangle}\right)^{3/2}\exp\left(-\frac{3R^2}{2\langle r^2\rangle}\right), $$
where $R$ is the end-to-end distance, and the mean square position of the units is $\langle r^2\rangle = N u^2$ where $N$ is the number of units in the chain and $u$ is ithe length of each unit. 
For simplicity, we'll work with $u=1$. 


## Simulating One Chain

The position of each link of the chain relative to the previous link can be described with angles $\theta\in[0,2\pi]$ and $\phi\in[0,pi]$ (think of $\theta$ as describing the direction in the XY plane and $\phi$ as describing the direction in the plane uniquely defined by the points $(0,0,0)$, $(x, y, 0)$, and $(x, y, z)$). In this case, $\phi$ need only cover $\pi$ radians. 

Without loss of generality, we can assume that the chain starts at the origin. 
Then, the end point in the chain can be described by a cumulative sum of a series of x, y, and z coordinates that are a function of $\theta_{n\times 1}$ and $\phi_{n\times 1}$:

$$\begin{array}{rcl} x &=& \cos(\theta)\sin(\phi)\\
y &=& \sin(\theta)\sin(\phi)\\
z &=& \cos(\phi)\end{array} $$

### Unconstrained Links Function

Write a function that takes $n$ and returns the distance between the start and end points of the chain. 
Use vector-based operations to increase the efficiency of your function.


### Unconstrained Links Distribution

Simulate 10000 chains and save the distribution
